from dataclasses import replace

import pytest

from seesaw.fdm import GCodePreview, profile_text
from seesaw.fdm_settings import FDMSettings
from seesaw.pipeline import PipelineError


@pytest.mark.parametrize("value", [True, float("nan"), float("inf"), -1, 400])
def test_filament_temperature_rejects_invalid(value):
    with pytest.raises(ValueError):
        replace(FDMSettings(), nozzle_c=value).validate()


def test_generated_profile_uses_explicit_units_and_no_postprocessing():
    result = profile_text(FDMSettings(nozzle_c=225, bed_c=70, infill_percent=22))
    assert "temperature = 225\n" in result
    assert "bed_temperature = 70\n" in result
    assert "fill_density = 22%\n" in result
    assert "post_process = \n" in result
    assert "use_relative_e_distances = 1\n" in result


def gcode(path, x=20):
    path.write_text(
        f";LAYER_CHANGE\n;Z:0.2\nG1 Z0.2\nG1 X10 Y10\nG1 X{x} Y10 E1\n"
        ";SEESAW_END_MODEL\nG1 X900 Y900 E1\n"
    )


def test_preview_reads_actual_body_and_ignores_park_moves(tmp_path):
    path = tmp_path / "candidate.gcode"
    gcode(path)
    preview = GCodePreview(path)
    assert preview.z_values == [0.2]
    assert preview.segment_counts == [1]
    assert preview.thumbnail(0).startswith(b"\x89PNG")
    with pytest.raises(ValueError):
        preview.thumbnail(-1)


def test_extrusion_outside_bed_is_blocked(tmp_path):
    path = tmp_path / "candidate.gcode"
    gcode(path, 251)
    with pytest.raises(PipelineError, match="build volume"):
        GCodePreview(path)


def test_empty_layer_is_blocked(tmp_path):
    path = tmp_path / "candidate.gcode"
    path.write_text(";LAYER_CHANGE\n;Z:0.2\nG1 X5 Y5\n")
    with pytest.raises(PipelineError, match="empty"):
        GCodePreview(path)


def test_native_settings_readback_rejects_changed_heat_and_truncation(tmp_path):
    from seesaw.fdm import validate_settings

    path = tmp_path / "candidate.gcode"
    text = (
        "; generated by PrusaSlicer 2.9.4\nM109 S210\nM190 S60\nM83\n"
        ";SEESAW_END_MODEL\n; temperature = 210\n; bed_temperature = 60\n"
        "; layer_height = 0.2\n; fill_density = 15%\n; perimeter_speed = 40\n"
        "; support_material = 0\n; use_relative_e_distances = 1\n"
    )
    path.write_text(text)
    validate_settings(path, FDMSettings())
    for changed in (
        text.replace("M109 S210", "M109 S250"),
        text.replace(";SEESAW_END_MODEL", ";incomplete"),
        text.replace("; fill_density = 15%", "; fill_density = 20%"),
        text.replace("M83", "M82"),
    ):
        path.write_text(changed)
        with pytest.raises(PipelineError):
            validate_settings(path, FDMSettings())
